In [1]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Original Matrix:")
print(matrix)
print("Flattened Matrix:")
print(matrix.flatten())

Original Matrix:
[[1 2 3]
 [4 5 6]]
Flattened Matrix:
[1 2 3 4 5 6]


In [2]:
import numpy as np

matrix = np.array([
    [1, 2],
    [3, 4]
])
print("Rank of Matrix:", matrix.ndim)

Rank of Matrix: 2
