In [1]:
import numpy as np
from scipy.sparse import csr_matrix
matrix = np.array([[1, 0, 0],
                   [0, 0, 2],
                   [0, 3, 0]])
sparse_matrix = csr_matrix(matrix)
print("Given Matrix:")
print(matrix)
print("Sparse Matrix:")
print(sparse_matrix)

Given Matrix:
[[1 0 0]
 [0 0 2]
 [0 3 0]]
Sparse Matrix:
  (0, 0)	1
  (1, 2)	2
  (2, 1)	3


In [ ]:
import numpy as np
from scipy.sparse import csr_matrix
matrix = np.array([[1, 0],
                   [0, 0],
                   [0, 3]])
sparse_matrix = csr_matrix(matrix)
print("Matrix:")
print(matrix)
print("Sparse Matrix:")
print(sparse_matrix)